// frontend/src/app/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core';
import {Router} from "@angular/router";
import {ApiService} from "../api.service";
import {AppComponent} from "../app.component";

@Component({
    selector: 'navbar',
    templateUrl: './navbar.component.html',
    styleUrls: ['./navbar.component.scss']
})
export class NavbarComponent implements OnInit {

    showNavBarMenu : Boolean = false ;

    constructor(private _apiService: ApiService, private router: Router, private app: AppComponent) { }

    logout(){
        this._apiService.logout();
        this.router.navigate(["/login"])
    }

    getPromotion(user){
        return "P" + parseInt(user.pseudo);
    }

    ngOnInit() {
        if(this.app.user == null){
            this.router.navigate(["/login"])
        }
    }
}

<div class="header py-4">
    <div class="container">
        <div class="d-flex">
            <a class="header-brand" routerLink="/">
                <img src="assets/images/logo-mines.png" class="header-brand-img" alt="site logo">
            </a>
            <div class="d-flex order-lg-2 ml-auto">
                <div class="dropdown">
                    <div class="nav-link pr-0 leading-none" (click)="showNavBarMenu = !showNavBarMenu">
                        <span class="avatar"></span>
                        <span class="ml-2 d-lg-block">
                            <span class="text-default">{{ user?.first_name }} {{ user?.last_name[0] }}</span>
                            <small class="text-muted d-block mt-1">P{{user?.promotion}}</small>
                        </span>
                    </div>
                    <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow" [ngClass]="{'show' : showNavBarMenu}">
                        <a class="dropdown-item" *ngIf="user" routerLink="/user/{{ user.id }}">
                            <i class="dropdown-icon fe fe-user"></i> Profil
                        </a>
                        <a class="dropdown-item" href="#">
                            <i class="dropdown-icon fe fe-settings"></i> Paramètres
                        </a>
                        <div class="dropdown-item" (click)="logout()">
                            <i class="dropdown-icon fe fe-log-out"></i> Déconnexion
                        </div>
                    </div>
                </div>
            </div>
            <a href="#" class="header-toggler d-lg-none ml-3 ml-lg-0" data-toggle="collapse" data-target="#headerMenuCollapse">
                <span class="header-toggler-icon"></span>
            </a>
        </div>
    </div>
</div>
<div class="header collapse d-lg-flex p-0" id="headerMenuCollapse">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg order-lg-first">
                <ul class="nav nav-tabs border-0 flex-column flex-lg-row">
                    <li class="nav-item">
						<a routerLink="/" class="nav-link" [ngClass]="{'active': isActive('^\/$')}"><i class="fe fe-home"></i>Accueil</a>
                    </li>
										
					<li class="nav-item dropdown" dropdown>
						<a dropdownToggle class="nav-link" [ngClass]="{'active': isActive('^\/association')}"><i class="fe fe-power"></i>Associations</a>
						<div *dropdownMenu class="dropdown-menu dropdown-menu-arrow">
								<a *ngFor="let association of list_associations_short" class="dropdown-item" routerLink="/associations/{{ association.id }}">{{association.name}}</a>
								<div class="dropdown-divider"></div>
								<a routerLink="/associations" class="dropdown-item">Toutes les associations</a>
						</div>
                    </li>
                    <li class="nav-item">
						<a routerLink="/users" class="nav-link" [ngClass]="{'active': isActive('^\/user')}"><i class="fe fe-users"></i>Trombinoscope</a>
                    </li>
                    <li class="nav-item">
						<a routerLink="/forum" class="nav-link" [ngClass]="{'active': isActive('^\/forum')}"><i class="fe fe-message-circle"></i>Forum</a>
                    </li>
                    <li class="nav-item">
						<a routerLink="/repartitions" class="nav-link" [ngClass]="{'active': isActive('^\/repartitions')}"><i class="fe fe-users"></i>Repartitions</a>

                    <li class="nav-item">
						<a routerLink="/rer" class="nav-link" [ngClass]="{'active': isActive('^\/rer')}"><i class="fe fe-clock"></i>Horaires RER B</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

// frontend/src/components/Navbar.tsx
import React, { useContext, useState } from "react";
import Logo from "../logo-mines.png";
import { Link, Redirect, useLocation } from "react-router-dom";
import BootstrapNavbar from "react-bootstrap/Navbar";
import NavDropdown from "react-bootstrap/NavDropdown";
import Container from "react-bootstrap/Container";

import "./navbar.css";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";
import { userService } from "../App";
import { UserContext } from "../services/userService";

/**
 * The links displayed in the navbar. It's an array of objects having three
 * properties each:
 *   * `icon`: the Bootstrap icon to display besides the navbar item. It's the
 *   part after `fe-` in the class name of the icon.
 *   * `url`: the URL of the link.
 *   * `label`: the text to display.
 */
const links = [
    { icon: "home", url: "/", label: "Accueil" },
    { icon: "zap", url: "/associations", label: "Associations" },
    { icon: "check-square", url: "/sondages", label: "Sondages" },
];

function Navbar() {
    const location = useLocation();
    const user = useContext(UserContext);
    const [redirectToLogin, setRedirectToLogin] = useState<boolean>(false);

    const logout = () => {
        userService.signOut().then(() => {
            setRedirectToLogin(true);
        });
    };

    if (redirectToLogin) {
        return <Redirect to={"/login"} />;
    }

    const linksComponent = links.map(({ icon, url, label }) => {
        let className = "";
        if (icon) {
            className = "fe fe-" + icon;
        }

        const isActive =
            url == "/"
                ? location.pathname == "/"
                : location.pathname.startsWith(url);

        return (
            <li className="nav-item" key={url}>
                <Link
                    to={url}
                    className={"nav-link" + (isActive ? " active" : "")}
                >
                    <i className={className} />
                    {label}
                </Link>
            </li>
        );
    });

    return user ? (
        <>
            <div className="header p-1">
                <Container>
                    <BootstrapNavbar expand="lg">
                        <BootstrapNavbar.Brand>
                            <Link to="/" className="header-brand">
                                <img
                                    src={Logo}
                                    className="header-brand-img"
                                    alt="Logo MINES ParisTech"
                                />
                            </Link>
                        </BootstrapNavbar.Brand>

                        <NavDropdown
                            className="ml-auto"
                            id="nav-dropdown"
                            bsPrefix="caret-off"
                            title={
                                <Container>
                                    <Row
                                        noGutters={true}
                                        className="align-items-center"
                                    >
                                        <Col>
                                            <span className="avatar" />
                                        </Col>
                                        <Col className="ml-2 float-right">
                                            <span className="text-default">
                                                {user.firstName} {user.lastName}
                                            </span>
                                            <small className="text-muted d-block mt-0 text-left">
                                                {`P${user.promotion}`}
                                            </small>
                                        </Col>
                                    </Row>
                                </Container>
                            }
                        >
                            <NavDropdown.Item href={`/profils/${user.id}`}>
                                <i className="dropdown-icon fe fe-user" />{" "}
                                Profil
                            </NavDropdown.Item>
                            <NavDropdown.Item>
                                <i className="dropdown-icon fe fe-settings" />{" "}
                                Paramètres
                            </NavDropdown.Item>
                            <NavDropdown.Divider />
                            <NavDropdown.Item onClick={logout}>
                                <i className="dropdown-icon fe fe-log-out" />{" "}
                                Déconnexion
                            </NavDropdown.Item>
                        </NavDropdown>
                    </BootstrapNavbar>
                </Container>
            </div>
            <div className="header p-0">
                <Container>
                    <Row className="align-items-center">
                        <Col>
                            <ul className="nav nav-tabs border-0 flex-column flex-lg-row">
                                {linksComponent}
                            </ul>
                        </Col>
                    </Row>
                </Container>
            </div>
        </>
    ) : null;
}

export default Navbar;
