// frontend/src/utils/navbar.tsx
import React, { useState } from "react";
import { Redirect } from "react-router-dom";

// @ts-ignore
import Logo from "../logo-mines.png";
import { Link } from "react-router-dom";

import {
    NavbarToggler,
    UncontrolledDropdown,
    DropdownToggle,
    DropdownMenu,
    DropdownItem
} from "reactstrap";
import { authService } from "../App";

function Navbar() {
    const [isOpen, setIsOpen] = useState<boolean>(true);
    const [redirectToLogin, setRedirectToLogin] = useState<boolean>(false);
    const toggle = () => setIsOpen(!isOpen);

    let barClassNames = "header d-lg-flex p-0";
    if (!isOpen) {
        barClassNames += " collapse";
    }

    const logout = () => {
        authService.signOut().then(() => {
            setRedirectToLogin(true);
        });
    };

    if (redirectToLogin) {
        return <Redirect to={"/login"} />;
    }

    return (
        <>
            <div className="header py-4">
                <div className="container">
                    <div className="d-flex">
                        <Link to="/" className="header-brand">
                            <img
                                src={Logo}
                                className="header-brand-img"
                                alt="site logo"
                            />
                        </Link>
                        <div className="d-flex order-lg-2 ml-auto">
                            <UncontrolledDropdown nav inNavbar>
                                <DropdownToggle nav className="text-left">
                                    <span className="avatar" />
                                    <span className="ml-2 d-lg-block">
                                        <span className="text-default">
                                            Adrien B.
                                        </span>
                                        <small className="text-muted d-block mt-0">
                                            P17
                                        </small>
                                    </span>
                                </DropdownToggle>
                                <DropdownMenu right>
                                    <DropdownItem>
                                        <i className="dropdown-icon fe fe-user" />{" "}
                                        Profil
                                    </DropdownItem>
                                    <DropdownItem>
                                        <i className="dropdown-icon fe fe-settings" />{" "}
                                        Paramètres
                                    </DropdownItem>
                                    <DropdownItem divider />
                                    <DropdownItem onClick={logout}>
                                        <i className="dropdown-icon fe fe-log-out" />{" "}
                                        Déconnexion
                                    </DropdownItem>
                                </DropdownMenu>
                            </UncontrolledDropdown>
                        </div>
                        <NavbarToggler
                            className="header-toggler d-lg-none ml-3 ml-lg-0"
                            onClick={toggle}
                        >
                            <span className="header-toggler-icon" />
                        </NavbarToggler>
                    </div>
                </div>
            </div>
            <div className={barClassNames}>
                <div className="container">
                    <div className="row align-items-center">
                        <div className="col-lg order-lg-first">
                            <ul className="nav nav-tabs border-0 flex-column flex-lg-row">
                                <li className="nav-item">
                                    <Link to="/" className="nav-link">
                                        <i className="fe fe-home" />
                                        Accueil
                                    </Link>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
}

export default Navbar;

// frontend/src/app/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core';
import {Router} from "@angular/router";
import {ApiService} from "../api.service";
import {AppComponent} from "../app.component";

@Component({
    selector: 'navbar',
    templateUrl: './navbar.component.html',
    styleUrls: ['./navbar.component.scss']
})
export class NavbarComponent implements OnInit {

    showNavBarMenu : Boolean = false ;

    constructor(private _apiService: ApiService, private router: Router, private app: AppComponent) { }

    logout(){
        this._apiService.logout();
        this.router.navigate(["/login"])
    }

    getPromotion(user){
        return "P" + parseInt(user.pseudo);
    }

    ngOnInit() {
        if(this.app.user == null){
            this.router.navigate(["/login"])
        }
    }
}

<div class="header py-4">
    <div class="container">
        <div class="d-flex">
            <a class="header-brand" routerLink="/">
                <img src="assets/images/logo-mines.png" class="header-brand-img" alt="site logo">
            </a>
            <div class="d-flex order-lg-2 ml-auto">
                <div class="dropdown">
                    <div class="nav-link pr-0 leading-none" (click)="showNavBarMenu = !showNavBarMenu">
                        <span class="avatar"></span>
                        <span class="ml-2 d-lg-block">
                            <span class="text-default">{{ user?.first_name }} {{ user?.last_name[0] }}</span>
                            <small class="text-muted d-block mt-1">P{{user?.promotion}}</small>
                        </span>
                    </div>
                    <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow" [ngClass]="{'show' : showNavBarMenu}">
                        <a class="dropdown-item" *ngIf="user" routerLink="/user/{{ user.id }}">
                            <i class="dropdown-icon fe fe-user"></i> Profil
                        </a>
                        <a class="dropdown-item" href="#">
                            <i class="dropdown-icon fe fe-settings"></i> Paramètres
                        </a>
                        <div class="dropdown-item" (click)="logout()">
                            <i class="dropdown-icon fe fe-log-out"></i> Déconnexion
                        </div>
                    </div>
                </div>
            </div>
            <a href="#" class="header-toggler d-lg-none ml-3 ml-lg-0" data-toggle="collapse" data-target="#headerMenuCollapse">
                <span class="header-toggler-icon"></span>
            </a>
        </div>
    </div>
</div>
<div class="header collapse d-lg-flex p-0" id="headerMenuCollapse">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg order-lg-first">
                <ul class="nav nav-tabs border-0 flex-column flex-lg-row">
                    <li class="nav-item">
						<a routerLink="/" class="nav-link" [ngClass]="{'active': isActive('^\/$')}"><i class="fe fe-home"></i>Accueil</a>
                    </li>
										
					<li class="nav-item dropdown" dropdown>
						<a dropdownToggle class="nav-link" [ngClass]="{'active': isActive('^\/association')}"><i class="fe fe-power"></i>Associations</a>
						<div *dropdownMenu class="dropdown-menu dropdown-menu-arrow">
								<a *ngFor="let association of list_associations_short" class="dropdown-item" routerLink="/associations/{{ association.id }}">{{association.name}}</a>
								<div class="dropdown-divider"></div>
								<a routerLink="/associations" class="dropdown-item">Toutes les associations</a>
						</div>
                    </li>
                    <li class="nav-item">
						<a routerLink="/users" class="nav-link" [ngClass]="{'active': isActive('^\/user')}"><i class="fe fe-users"></i>Trombinoscope</a>
                    </li>
                    <li class="nav-item">
						<a routerLink="/forum" class="nav-link" [ngClass]="{'active': isActive('^\/forum')}"><i class="fe fe-message-circle"></i>Forum</a>
                    </li>
                    <li class="nav-item">
						<a routerLink="/repartitions" class="nav-link" [ngClass]="{'active': isActive('^\/repartitions')}"><i class="fe fe-users"></i>Repartitions</a>

                    <li class="nav-item">
						<a routerLink="/rer" class="nav-link" [ngClass]="{'active': isActive('^\/rer')}"><i class="fe fe-clock"></i>Horaires RER B</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
